apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ratings.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          # Docker Registry
          image: {{ .Values.ratings.image }}:{{ .Values.ratings.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.ratings.port }}
              name: web-port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.ratings.healthCheckPath }}
              port: {{ .Values.ratings.port }}
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: {{ .Values.ratings.healthCheckPath }}
              port: {{ .Values.ratings.port }}
              scheme: HTTP
          env:
            # - name: SERVICE_VERSION
            #   value: v1
            - name: SERVICE_VERSION
              value: {{ .Values.extraEnv.SERVICE_VERSION }}
            - name: MONGO_DB_URL
              value: {{ .Values.extraEnv.MONGO_DB_URL }}
            - name: MONGO_DB_USERNAME
              value: {{ .Values.extraEnv.MONGO_DB_USERNAME }}
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ratings.mongodbPasswordExistingSecret }}
                  key: mongodb-password

      imagePullSecrets:
        - name: {{ .Values.ratings.imagePullSecrets }}
